Check for function before creating it

diff --git a/script/push_lambda b/script/push_lambda
--- a/script/push_lambda
+++ b/script/push_lambda
@@ -28,14 +28,29 @@ function build_package() {
     echo "${dest}/package.zip"
 }
 
-
-function main() {
-    # Check usage
-    usage "$@"
-
+function exists() {
+    # Returns true if function already exists
     function_name="$1"
-    path="$2"
-    package=$( build_package "${path}" )
+
+    # Attempt to get-function, this will return a non-zero exist code if
+    # the function doesn't exist
+    aws lambda get-function --function-name "${function_name}" >/dev/null 2>&1
+
+    if [[ $? -eq 0 ]]
+    then
+        # get-function didn't error, therefore function exists, return true
+        # 0 = true!
+        return 0
+    else
+        # get-function errored, therefore function does not exist, return false
+        # 1 = false!
+        return 1
+    fi
+}
+
+function create() {
+    function_name="$1"
+    package="$2"
 
     # Copy package to S3
     aws s3 cp "${package}" s3://wintronio/lambda/ >/dev/null
@@ -51,8 +66,25 @@ function main() {
 
     # Create function on Lambda
     aws lambda create-function ${opts[@]}
+}
 
-    # echo "${function_name} pushed... ${package}"
+function main() {
+    # Check usage
+    usage "$@"
+
+    function_name="$1"
+    path="$2"
+
+    # Build package from path
+    package=$( build_package "${path}" )
+
+    if exists "$function_name"
+    then
+        echo "$function_name exists, delete it first"
+        exit 0
+    else
+        create "$function_name" "$package"
+    fi
 }
 
 main "$@"
